import os  # isort:skip
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for vhc_blog project.

Generated by 'django-admin startproject' using Django 1.11.24.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wb^=%$c=7^3)0z8(x-n7qz+prd$@@t=v+18m50gmaw#bolf8u3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

ROOT_URLCONF = 'vhc_blog.urls'


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'vhc_blog', 'static'),
)
SITE_ID = 1


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'vhc_blog', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader'
            ],
        },
    },
]


MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_column',
    'djangocms_file',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'redactor',
    'vhc_blog',
    'core',
    'django_comments',
]

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
)

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'code': 'en',
            'name': gettext('en'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
    ],
    'default': {
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}

CMS_TEMPLATES = (
    ## Customize this
    ('home.html', 'Home'),
    ('post_content.html', 'Content'),
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {
# #home page  plugins
    'home_gallery': {
        "plugins": 'CMSHomeGallaryPlugin',
        "name": gettext("HomeGallary")
    },
    'home_recent_Post': {
        "plugins": 'CMSHomeRecentPostPlugin',
        "name": gettext("HomeRecentPost")
    },
    'home_most_read': {
        "plugins": 'CMSHomeMostReadPlugin',
        "name": gettext("HomeMostRead")
    },
    'side_featured_Post': {
        "plugins": 'CMSHomeFeaturedPostPlugin',
        "name": gettext("FeaturedPost")
    },
    'side_blog_category': {
        "plugins": 'CMSHomeCategoryPlugin',
        "name": gettext("BlogCategories")
    },
    'post_header': {
        "plugins": 'CMSPostHeaderPlugin',
        "name": gettext("PostHeader")
    },
    'post_content': {
        "plugins": 'CMSPostContentPlugin',
        "name": gettext("PostContent ")
    },
    'post_archive': {
        "plugins": 'CMSPostArchivePlugin',
        "name": gettext("PostArchive")
    },
    'post_author': {
        "plugins": 'CMSPostAuthorPlugin',
        "name": gettext("Post Author")
    },
    'post_comment': {
        "plugins": 'CMSPostCommentPlugin',
        "name": gettext("Post Comment")
    },
    'ad_banner_350x200': {
        "plugins": 'AdBanner300X250Plugin',
        "name": gettext("AdBanner_300x250")
    },  
    'ad_banner_728x90': {
        "plugins": 'AdBanner728X90Plugin',
        "name": gettext("AdBanner_728x90")
    },
}

REDACTOR_UPLOAD = 'uploads/'
REDACTOR_OPTIONS = {'plugins': ['source', 'fontcolor', 'inlinestyle', 'fontsize', 'fontfamily',
                                'imagemanager', 'filemanager', 'definedlinks', 'textdirection', 'alignment', 'table']}

DATABASES = {
    'default': {
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'NAME': 'vhc_blog',
        'PASSWORD': 'vhc',
        'PORT': '',
        'USER': 'vhc'
    }
}

MIGRATION_MODULES = {
    
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)
